### ISSUE TITLE
This app is blocked

### ISSUE THREAD

**Issue by wulfland** [GoogleCloudPlatform/fourkeys#197] opened 2021-09-02 16:34 UTC
I just tried to install 4keys and I came to the point where I should authorize the connector. But I receive the following error: `This app is blocked`.

I'm new to gcloud - so maybe I've missed something. But I'm stuck in the setup.

<img width="920" alt="2021-09-02_18-28-41" src="https://user-images.githubusercontent.com/5276337/131882230-dbcef4cb-10f9-4f0a-b711-f7d80324c331.png">

**Comment by dinagraves** [comment] 2021-09-08 03:02
Hi there! I'm so sorry about that.  This is a duplicate of an old issue.  Luckily we have a PR for the fix now!  https://github.com/GoogleCloudPlatform/fourkeys/pull/204

**Comment by dinagraves** [comment] 2021-09-08 03:03
Duplicate of https://github.com/GoogleCloudPlatform/fourkeys/issues/86

**Closed by dinagraves** 2021-09-08 03:03 UTC
