### ISSUE TITLE
Incidents table shows error: invalid timestamp

### ISSUE THREAD

**Issue by vincentvanrijn** [GoogleCloudPlatform/fourkeys#258] opened 2022-01-06 13:29 UTC
Hi Fourkeys. I found a next bug in the software: Incidents are not shown in the incidents table.(They are in the events_raw) When I open my grafana  dashboard I see a warning at the 'median time to Change': invalidQuery: Invalid timestamp: '2022-01-06 13:10:47 +0100' .Also when I query the incidents table I get the same error. Hope you can fix it (edited) 
![Screenshot 2022-01-06 at 14 27 06](https://user-images.githubusercontent.com/11926539/148390134-ad5f9a84-56b9-40f9-9030-6140737238f9.png)
![Screenshot 2022-01-06 at 14 23 50](https://user-images.githubusercontent.com/11926539/148390136-a1a8c00a-595a-4e1d-9918-40f550ae3afa.png)

**Comment by dinagraves** [comment] 2022-01-06 19:16
Thank you! This is a duplicate of #257.

**Closed by dinagraves** 2022-01-06 19:16 UTC
