### ISSUE TITLE
Data Studio not able to authorise community connector

### ISSUE THREAD

**Issue by AbinayaSubba** [GoogleCloudPlatform/fourkeys#134] opened 2021-05-31 03:31 UTC
I'm trying to do small exercise following below links https://github.com/GoogleCloudPlatform/fourkeys/blob/main/setup/INSTALL.md#collecting-changes-data .

However i get below message when trying to authorize from this page
![image](https://user-images.githubusercontent.com/45870002/120135836-b4862700-c1ee-11eb-9ab8-e59ce0b850c2.png)

"This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access."

Please advise

**Comment by wpannell** [comment] 2021-05-31 06:42
I'm getting this too.  Cannot tell if I did something wrong.

How can I reset and restart to rule out my own human error?

Is this an issue you can reproduce?

**Comment by dinagraves** [comment] 2021-06-01 17:43
Duplicate of https://github.com/GoogleCloudPlatform/fourkeys/issues/86

So sorry!  We have a workaround available: https://github.com/GoogleCloudPlatform/fourkeys/issues/86#issuecomment-823574890.

**Closed** 2021-06-01 17:43 UTC
Labels: duplicate, priority: p1, type: question
